# Numpy Array

In [2]:
import numpy as np
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [3]:
#Upcasting:

In [4]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [5]:
#two dimensions

In [6]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [7]:
#Minimum dimensions 2:

In [8]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [9]:
#dtype

In [10]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [11]:
#Data-type consisting of more than one element:

In [12]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [13]:
type(x[1][0])

numpy.int16

In [14]:

#Creating an array from sub-classes:

In [15]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [16]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [17]:
#Convert the input to an array.

In [18]:
#Convert a list into an array:

In [19]:
 a = [1, 2]
type(a)

list

In [20]:
type(np.asarray(a))

numpy.ndarray

In [21]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [22]:
np.asarray((1,2))

array([1, 2])

In [23]:
#If dtype is set, array is copied only if dtype does not match:

In [24]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [25]:
np.asarray([1,2]) is a

False

In [26]:
np.asarray([1,2])

array([1, 2])

In [27]:
np.asarray(a, dtype=np.float64) is a

False

In [28]:
# ndarray subclasses are not passed through

In [29]:
issubclass(np.matrix, np.ndarray)

True

In [30]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [31]:
np.asarray(a) is a

False

In [32]:
np.asanyarray(a) is a

True

In [33]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

In [34]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [35]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [36]:
np.asanyarray([1,2]) is a

False

In [37]:
np.array(a, copy=True)  

array([[1, 2]])

In [38]:
#Create an array x, with a reference y and a copy z:

In [39]:
x = np.array([1, 2, 3])
x


array([1, 2, 3])

In [40]:
y = x

In [41]:
z = np.copy(x)

In [42]:
y[0] = 100
x

array([100,   2,   3])

In [43]:
y

array([100,   2,   3])

In [44]:
id(x[0])

2637436958352

In [45]:
id(y[0])

2637436959056

In [46]:
id(x) 

2637437241744

In [47]:
id(y)

2637437241744

# numpy.fromfunction

In [48]:
#Construct an array by executing a function over each coordinate.

In [169]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [170]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [51]:
#Create a new 1-dimensional array from an iterable object.

In [171]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x00000266138934C8>

In [172]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [54]:
#A new 1-D array initialized from text data in a string

In [173]:
a = np.fromstring('234 234',sep=' ')
a[0]

234.0

In [176]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [57]:
# How to create create a record array from a (flat) list of arrays

In [58]:
x1=np.array([1,2,3,4])

In [177]:
x2=np.array(['a','dd','xyz','12'])

In [178]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [179]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([( 1, 'a', 1.1, 1.1), (34, 'dd', 2. , 2. ),
           ( 3, 'xyz', 3. , 3. ), ( 4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [180]:
print(r[1]["a"])

34


In [181]:
x1[1]=34

In [182]:
x1[1]

34

# data types

In [183]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [184]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [185]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [186]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [187]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [188]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [71]:
list(range(50,-1,5))

[]

In [72]:
print("Numbers spaced apart by 2:",np.arange(50,-1,-2)) # Numbers spaced apart by 2

Numbers spaced apart by 2: [50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2  0]


In [73]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [74]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [189]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,21)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


# Matrix creation

In [190]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [191]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [192]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [193]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [194]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [195]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [196]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [197]:
np.arange(3)

array([0, 1, 2])

In [198]:
np.arange(3.0)

array([0., 1., 2.])

In [200]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [86]:
np.arange(3,7,2)

array([3, 5])

In [202]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [206]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [89]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [207]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [208]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [209]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [210]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [94]:
#Extract a diagonal or construct a diagonal array.

In [214]:
x = np.arange(16).reshape((-1,4))

In [215]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [216]:
np.diag(x)

array([ 0,  5, 10, 15])

In [220]:
np.diag(x, k=2)

array([2, 7])

In [221]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [224]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [101]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [225]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [103]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [104]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [226]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [227]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [107]:
#return a Lower triangle of an array.

In [228]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [109]:
#return Upper triangle of an array.

In [229]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [235]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.58393462 0.24349532 0.81553689]
 [0.3204981  0.97328853 0.38802692]]


In [237]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-1.34278884  0.35893963  0.2298906 ]
 [ 2.12382818 -0.82828731  0.49255628]
 [ 0.72847533 -1.56299064 -1.06664727]
 [-0.08318686  0.21395945 -1.9318828 ]]


In [238]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 3

Random integer matrix


In [114]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[80 47 51 45]
 [64 42  4 68]
 [13 99 38 55]
 [31 99 37 54]]

20 samples drawn from a dice throw: [5 6 6 1 1 4 3 3 2 1 3 2 4 4 1 6 6 1 3 4]


# Reshaping

In [240]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[10, 77, 56, 58, 96],
       [35, 92, 64, 81, 32],
       [73, 20, 39, 19, 42],
       [32, 29, 83, 33, 41],
       [82, 50, 34,  4, 45],
       [75,  7, 22, 55, 58]])

In [241]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [243]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [10 77 56 58 96 35 92 64 81 32 73 20 39 19 42 32 29 83 33 41 82 50 34  4
 45 75  7 22 55 58] 
 --------------------

b looks like
 -------------------- 
 [[[10 77 56 58 96]
  [35 92 64 81 32]
  [73 20 39 19 42]]

 [[32 29 83 33 41]
  [82 50 34  4 45]
  [75  7 22 55 58]]] 
 --------------------

c looks like
 -------------------- 
 [[10 77 56 58 96]
 [35 92 64 81 32]
 [73 20 39 19 42]
 [32 29 83 33 41]
 [82 50 34  4 45]
 [75  7 22 55 58]] 
 --------------------


In [244]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [56 20 14 89 13 83 60 62 89 95]

Here is the sorted vector
 -------------------------------------------------- 
 [13 14 20 56 60 62 83 89 89 95]


In [245]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 3 55 70 90 91]
 [19 23 30 66 90]
 [16 43 48 63 82]
 [ 4 25 71 75 76]
 [13 19 57 62 89]]


array([[70, 90, 55, 91,  3],
       [90, 19, 66, 23, 30],
       [43, 82, 16, 63, 48],
       [75, 25, 76,  4, 71],
       [89, 62, 19, 13, 57]])

In [246]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 91
Max of b: 96


array([[[10, 77, 56, 58, 96],
        [35, 92, 64, 81, 32],
        [73, 20, 39, 19, 42]],

       [[32, 29, 83, 33, 41],
        [82, 50, 34,  4, 45],
        [75,  7, 22, 55, 58]]])

In [247]:
M

array([[70, 90, 55, 91,  3],
       [90, 19, 66, 23, 30],
       [43, 82, 16, 63, 48],
       [75, 25, 76,  4, 71],
       [89, 62, 19, 13, 57]])

In [248]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [3 0 1 2 0]
Max of b location: 4
Max of c location: 4


# Indexing and slicing

In [249]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [250]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [251]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [253]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [254]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [255]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [256]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [257]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [259]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[56 29 90 31 36]
 [77 50 16 51 11]
 [50 58 19 52 63]]


array([[29, 31],
       [50, 51],
       [58, 52]])

In [262]:
mat[0:3,[1,3]]
mat

array([[56, 29, 90, 31, 36],
       [77, 50, 16, 51, 11],
       [50, 58, 19, 52, 63]])

In [266]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 1:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 1: 50


array([[56, 29, 90, 31, 36],
       [77, 50, 16, 51, 11],
       [50, 58, 19, 52, 63]])

In [269]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 16

Row or column extract
----------------------


In [274]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

Entire row at index 2: [50 58 19 52 63]
Entire column at index 3: [31 51 52]


In [279]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[51 11]
 [52 63]]


In [278]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[29 31]
 [50 51]]


# Subseting

In [282]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[39 14 39 63 81]
 [54 61 40 60 55]
 [56 49 19 23 28]]


array([[False, False, False,  True,  True],
       [ True,  True, False,  True,  True],
       [ True, False, False, False, False]])

In [283]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [63 81 54 61 60 55 56]


# Slicing

In [285]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [141]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [286]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [287]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [288]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)
    


Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [145]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [146]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [289]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [290]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[2 7 1]
 [1 7 2]
 [2 2 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 4 4]
 [4 7 1]
 [9 8 5]]


In [291]:
mat1*mat2

array([[ 6, 28,  4],
       [ 4, 49,  2],
       [18, 16, 40]])

In [292]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[43 65 20]
 [49 69 21]
 [86 86 50]]


In [293]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\nathi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [294]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[102 107 101]
 [101 107 102]
 [102 102 108]]


In [295]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[  8 343   1]
 [  1 343   8]
 [  8   8 512]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[  8 343   1]
 [  1 343   8]
 [  8   8 512]]


# Broadcasting

In [154]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [304]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [305]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [306]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [307]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [308]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [309]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [311]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[4 6 3]
 [2 5 7]
 [6 2 1]]

2nd Matrix of random single-digit numbers
------------
 [[9 2 3]
 [1 6 6]
 [3 6 1]]


In [312]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.         2.44948974 1.73205081]
 [1.41421356 2.23606798 2.64575131]
 [2.44948974 1.41421356 1.        ]]


In [314]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[  54.59815003  403.42879349   20.08553692]
 [   7.3890561   148.4131591  1096.63315843]
 [ 403.42879349    7.3890561     2.71828183]]


In [318]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.60205999 0.77815125 0.47712125]
 [0.30103    0.69897    0.84509804]
 [0.77815125 0.30103    0.        ]]
[[4 6 3]
 [2 5 7]
 [6 2 1]]
[[9 2 3]
 [1 6 6]
 [3 6 1]]


In [319]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[4 0 0]
 [0 5 1]
 [0 2 0]]


array([[4, 0, 0],
       [0, 5, 1],
       [0, 2, 0]], dtype=int32)

In [320]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [321]:
A = np.linspace(0,12*np.pi,1001)


In [168]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])